### ISSUE TITLE
Statement of not storing API keys: API KEYは保管してないの記述を

### ISSUE THREAD

**Issue by shinokada** [himanushi/chat-code#1]
Having the statement "We do not store API keys" definitely reassures users, doesn't it?
やはり”API KEYは保管していません”の記述があった方が使う方も安心ですね。

**Comment by himanushi** [comment]
@shinokada 
Thank you! I will make an addition! Grateful!
ありがとうございます！追記いたします！！感謝！

**Comment by himanushi** [comment]
@shinokada 
Thank you for your comment! I have addressed the issue.
コメントありがとうございます！対応しました。
https://chat-c.netlify.app/me
https://github.com/himanushi/chat-code/commit/493259681ac0abd76a78e54914740c2cbabf97f7
