### ISSUE TITLE
Mobile UI looks not user friendly.

### ISSUE THREAD

**Issue by kentny** [himanushi/chat-code#14]
The app itself is amazing, but I could not find a way to start the conversation on a mobile screen that is placed under a humbarger menu.
It'd be great if the way to do it more quickly even on a mobile screen.

**Comment by himanushi** [comment]
@kentny
<img width="512" alt="スクリーンショット 2023-03-11 15 29 14" src="https://user-images.githubusercontent.com/27812830/224469854-32d8f5cc-b83f-4229-89d0-a70b8d0da9a4.png">

I have addressed your request. With this, you should now be able to start chatting immediately even after entering your API key! https://github.com/himanushi/chat-code/pull/15

https://chat-c.netlify.app/me
