### ISSUE TITLE
Add English translation

### ISSUE THREAD

**Issue by shinokada** [himanushi/chat-code#2]
It will be more friendly for English speakers to add an English translation because your app can be popular.
これ人気になる可能性があるので、英語を使う人用に英語の翻訳を追加するのはどうでしょうか。

**Comment by himanushi** [comment]
Thank you for the comment! I was trying to make i18n support, and I think https://github.com/kaisermann/svelte-i18n looks good.
コメントありがとうございます！i18n対応しようとしてました。
https://github.com/kaisermann/svelte-i18n が良さそうな気がしています。

**Comment by himanushi** [comment]
@shinokada 
I have implemented i18n support!
i18n 対応しました！

https://github.com/himanushi/chat-code/pull/4
https://chat-c.netlify.app
