### ISSUE TITLE
[Request] Programming Language Preset feature.

### ISSUE THREAD

**Issue by kentny** [himanushi/chat-code#30]
I write "in JavaScript" lots of times when I ask questions about programming.

ex)
```
- How to load json object from a file in javascript.
- How to write a class definition in javascript.
```

I'd say that I don't have to write `in {Language}` lots of times when the conversation mode is on since chatGPT can understand the context, but I don't want to turn it on in order to save the consumption of tokens.
What do you think to implement the language preset feature to insert the precondition in the prompt sent to ChatGPT?

**Comment by himanushi** [comment]
@kentny 
Thank you for the great idea! A message template was already scheduled for implementation, and I believe this feature will likely solve the problem. When in conversation mode 'on', the message template will be used only for the initial chat, and for 'off' mode, it will be implemented to use the message template every time.

**Comment by himanushi** [comment]
@kentny 
Implementation is complete! Closing now.
https://github.com/himanushi/chat-code/pull/31

**Comment by kentny** [comment]
@himanushi 
Thanks!
